spring:
  application:
    name: morsel
  datasource:
    url: jdbc:postgresql://localhost:5432/morsel
    username: morsel
    password: secret
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  mvc:
    problemdetails:
      enabled: true
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}